# https://www.youtube.com/watch?v=M_VuXVErD6E&list=PLfCL9tw4dakOI4RGirPnbMfJmBJetJe2w&index=46&t=1136s
# node src/cli.js input/config-flipper.yaml -o output/flipper

points:
   key:
      padding: cy
      footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
                hotswap: true
   zones:
    board:
      rows:
        bottom:
        home:
        top:
      columns:
          pinkie:
             spread: cx
             rows: 
              bottom:
                # bind: [0, 0, 0, 1]
                column_net: P21
              home:
                # bind: [0.5, 3, 3, 1]
                column_net: P20
              top: 
                column_net: P17
          ring:
            spread: cx
            rows: 
              bottom:
                bind: [0, 0, 19, 0] # top, right, bottom, left
                column_net: P19
              home: 
                # bind: [3,0,3,1]
                column_net: P18
              top: 
                # bind: [0.5,3,0,1]
                column_net: P15
          middle: 
            spread: cx
            rows: 
              bottom:
                bind: [0, 0, 19, 0] # top, right, bottom, left
                column_net: P14
              home: 
                # bind: [3,0,3,0]
                column_net: P16
              top:
                column_net: P10
                # bind: [0.5,1,0,1]
          index: 
            spread: cx
            rows: 
              bottom:
                bind: [0, 0, 19, 0] # top, right, bottom, left
                column_net: P4
              home: 
                # bind: [3,0,3,0]
                column_net: P5
              top: 
                # bind: [0.5,1,3,3]
                column_net: P6
          far: 
            spread: cx
            rows: 
              bottom:
                # bind: [3,1, 0, 73]
                column_net: P9
              home: 
                # bind: [3,1,3,0]
                column_net: P7 
              top: 
                # bind: [0.5,1,3,3]
                column_net: P8
    thumb:
      anchor:
        ref: board_index_bottom
        shift: [-0.35cx, -1cy]
      rows:
        home:
      columns:
        home:
          spread: cx
          rows:
            home:
              column_net: P3
              
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1.06cx , 1.06cy]
    cutout:
      - type: outline
        name: raw
        fillet: 1
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false               
pcbs:
  flipper:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        type: promicro
        anchor:
          ref: board_index_bottom
          shift: [-1.5cx, -1.1cy]
          rotate: 0
        params:
          orientation: down
      pcm12:
        type: pcm12
        anchor:
          ref: board_index_bottom
          shift: [-0.25cx, -1.5cy]
          rotate: 0
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true 
      via3:
        type: via
        anchor: 
          ref: board_index_bottom
          shift: [-0.5cx, -0.9cy]
        nets: 
          net: RAW 
      via4:
        type: via
        anchor: 
          ref: board_index_bottom
          shift: [-0.5cx, -1.2cy]
          # shift: [-4,-10]
        nets: 
          net: pos 
      via5:
        type: via
        anchor: 
          ref: board_index_bottom
          shift: [0cx, -0.9cy]
        nets: 
          net: GND 
      via6:
        type: via
        anchor: 
          ref: board_index_bottom
          shift: [0cx, -1.2cy]
        nets: 
          net: RST 
      b3u1000p:
        type: b3u1000p
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: board_index_bottom
          shift: [-0.27cx, -.7cy]
          rotate: 0
        params:
          reverse: true 
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: board_index_bottom
          shift: [-0.27cx, -0.95cy]
          rotate: 90
