# https://www.youtube.com/watch?v=M_VuXVErD6E&list=PLfCL9tw4dakOI4RGirPnbMfJmBJetJe2w&index=46&t=1136s

points:
   key:
      padding: cy
      footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
                hotswap: true
   zones:
    board:
      rows:
        bottom:
        home:
        top:
      columns:
        pinkie:
          spread: cx
          rows:
            bottom:
              column_net: P21
            home:
              column_net: P20
            top: 
              column_net: P17
        ring:
          spread: cx
          rows: 
            bottom:
              column_net: P19
            home: 
              column_net: P18
            top: 
              column_net: P15
        middle: 
          spread: cx
          rows: 
            bottom:
              column_net: P14
            home: 
              column_net: P16
            top:
              column_net: P10
        index: 
          spread: cx
          rows: 
            bottom:
              column_net: P4
            home: 
              column_net: P5
            top: 
              column_net: P6
        far: 
          spread: cx
          rows: 
            bottom:
              column_net: P9
            home: 
              column_net: P7 
            top: 
              column_net: P8
    thumb:
      anchor:
        ref: board_index_bottom
        shift: [0.7cx, 1.14cy]
      rows:
        home:
      columns:
        home:
          spread: cx
          rows:
            home:
              column_net: P3
              
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1cx , 1cx]
    cutout:
      - type: outline
        name: raw
        fillet: 2
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false               
pcbs:
  flipper:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        type: promicro
        anchor:
          ref: board_far_home
          shift: [-25, -17]
          rotate: 0
        params:
          orientation: down
      pcm12:
        type: pcm12
        anchor:
          ref: board_far_home
          shift: [-75, -22]
          rotate: 0
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true 
      via3:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [-2,-10]
        nets: 
          net: RAW 
      via4:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [-4,-10]
        nets: 
          net: pos 
      via5:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [8,-10]
        nets: 
          net: GND 
      via6:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [6,-10]
        nets: 
          net: RST 
      b3u1000p:
        type: b3u1000p
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: board_pinkie_bottom
          shift: [7, -15]
          rotate: 0
        params:
          reverse: true 
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: board_far_bottom
          shift: [-42 , -0]
          rotate: 0
